[package]
name = "bau-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.4.6" , features = ["derive"] }
regex = "1"
lazy_static = "1"
colored = "2.0.4"
