[package]
name = "bau"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1"
lazy_static = "1"
colored = "2"
 