[package]
name = "bau-language-server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
tower-lsp = "0.20.0"
serde_json = "1.0"